[package]
name = "habit_territories"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "C:\\Users\\suraf\\Documents\\Aptos-projects\\Habit-\\aptos-core\\aptos-move\\framework\\aptos-framework" }
AptosStdlib = { local = "C:\\Users\\suraf\\Documents\\Aptos-projects\\Habit-\\aptos-core\\aptos-move\\framework\\aptos-stdlib" }
MoveStdlib = { local = "C:\\Users\\suraf\\Documents\\Aptos-projects\\Habit-\\aptos-core\\aptos-move\\framework\\move-stdlib" }

[addresses]
HabitTerritories = "0x0416f59263fa4f4c52cfa45b89fcb47fa2eebef78cfda644bb3b8a19f0a4f3c6"  # Replace "0x1" with a specific address when deploying